---
title: "Extract Initial data files"
output: html_document
---

```{r setup-vars, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSQLite)
library(readxl)
library(officer)

#con <- dbConnect(drv=RSQLite::SQLite(), dbname='CodexProjectTracking/projectruns.sqlite')
#dbListTables() 
```



```{r prepare_excel, fig.width=6, fig.height=3 }
#list.files("data")
my_data <- read_excel("data/CODEX Experiment Master List_edit KRM.xlsx")
nrow(my_data)
colnames(my_data) <- gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',colnames(my_data))))))

tmp <- my_data[,c("Acquisition_Name","ROI")] %>% distinct() %>% mutate(id = row_number())
my_data <- merge(my_data, tmp, all=T) %>% rename(Experiment_Number = Experimentnumber)

# dbWriteTable(con, "Acquisition", tmp, overwrite=TRUE)
```


```{r prepare_ppt1, fig.width=6, fig.height=3 }
#f <- read_pptx("data/2020-05-19_234357-2x TMA_Bleached_13May2020-reg001.pptx")
f <- pptx_summary("data/2020-05-19_234357-2x TMA_Bleached_13May2020-reg001.pptx")
# class(f)

## Slide 1
t <- f %>% filter(slide_id == 1 & id == "3")
Acquisition_Name <- t$text[1]
pptTitle <- paste(t$text, collapse = "|")

## Slide 2
t <-  f %>% filter(slide_id == 2 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ExperimentMetadataTable <- t[2,]
colnames(ExperimentMetadataTable) <- paste0('ExperimentMetadata_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

## Slide 2
t <-  f %>% filter(slide_id == 3 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ProcessingParametersTable <- t[2,]
colnames(ProcessingParametersTable) <-  paste0('ProcessingParameters_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

summarySlides <- f %>% filter(grepl("^Summary Table",text))

#i = summarySlides$slide_id[1]
allSummary <- data.frame()
for(i in summarySlides$slide_id){
  t <- f %>% filter(slide_id == i & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) 
  allSummary <- rbind(allSummary,t)
}

title <- allSummary %>% filter(row_id == 1) %>% slice(1)
allSummary <- allSummary %>% filter(row_id > 1)
colnames(allSummary) <- paste0('Metrics_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[%#\\/]",'', title[1,]))))))


metricsTable1 <- cbind(Acquisition_Name,pptTitle,ExperimentMetadataTable,ProcessingParametersTable,allSummary)

```




```{r prepare_ppt2, fig.width=6, fig.height=3 }
#f <- read_pptx("data/2020-05-19_234357-2x TMA_Bleached_13May2020-reg001.pptx")
f <- pptx_summary("data/2020-05-19_235051-2x TMA_Bleached_13May2020-reg002.pptx")
# class(f)

## Slide 1
t <- f %>% filter(slide_id == 1 & id == "3")
Acquisition_Name <- t$text[1]
pptTitle <- paste(t$text, collapse = "|")

## Slide 2
t <-  f %>% filter(slide_id == 2 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ExperimentMetadataTable <- t[2,]
colnames(ExperimentMetadataTable) <- paste0('ExperimentMetadata_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

## Slide 2
t <-  f %>% filter(slide_id == 3 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ProcessingParametersTable <- t[2,]
colnames(ProcessingParametersTable) <-  paste0('ProcessingParameters_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

summarySlides <- f %>% filter(grepl("^Summary Table",text))

#i = summarySlides$slide_id[1]
allSummary <- data.frame()
for(i in summarySlides$slide_id){
  t <- f %>% filter(slide_id == i & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) 
  allSummary <- rbind(allSummary,t)
}

title <- allSummary %>% filter(row_id == 1) %>% slice(1)
allSummary <- allSummary %>% filter(row_id > 1)
colnames(allSummary) <- paste0('Metrics_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[%#\\/]",'', title[1,]))))))


metricsTable2 <- cbind(Acquisition_Name,pptTitle,ExperimentMetadataTable,ProcessingParametersTable,allSummary)

```




```{r prepare_ppt2, fig.width=6, fig.height=3 }
#f <- read_pptx("data/2020-05-19_234357-2x TMA_Bleached_13May2020-reg001.pptx")
f <- pptx_summary("data/2020-05-19_235742-2x TMA_Bleached_13May2020-reg003.pptx")
# class(f)

## Slide 1
t <- f %>% filter(slide_id == 1 & id == "3")
Acquisition_Name <- t$text[1]
pptTitle <- paste(t$text, collapse = "|")

## Slide 2
t <-  f %>% filter(slide_id == 2 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ExperimentMetadataTable <- t[2,]
colnames(ExperimentMetadataTable) <- paste0('ExperimentMetadata_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

## Slide 2
t <-  f %>% filter(slide_id == 3 & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) %>% filter(row_id > 1) %>% select(-row_id) %>% t() %>% as.data.frame()
t <- data.frame(lapply(t, as.character), stringsAsFactors=FALSE)[]
ProcessingParametersTable <- t[2,]
colnames(ProcessingParametersTable) <-  paste0('ProcessingParameters_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[#\\/]",'',t[1,]))))))

summarySlides <- f %>% filter(grepl("^Summary Table",text))

#i = summarySlides$slide_id[1]
allSummary <- data.frame()
for(i in summarySlides$slide_id){
  t <- f %>% filter(slide_id == i & content_type == 'table cell') %>% select(text,cell_id,row_id) %>% spread(cell_id,text) 
  allSummary <- rbind(allSummary,t)
}

title <- allSummary %>% filter(row_id == 1) %>% slice(1)
allSummary <- allSummary %>% filter(row_id > 1)
colnames(allSummary) <- paste0('Metrics_',  gsub(' ','_',trimws(gsub(' \\(µM\\)','',gsub("[\r\n]", "", gsub("[%#\\/]",'', title[1,]))))))


metricsTable3 <- cbind(Acquisition_Name,pptTitle,ExperimentMetadataTable,ProcessingParametersTable,allSummary)

```



```{r merge_all, fig.width=6, fig.height=3 }
metricsTables <- rbind(metricsTable1,metricsTable2,metricsTable3)

allData <- merge(my_data,metricsTable,by.x = c("Acquisition_Name","ROI","Cycle","Channel"),by.y = c("Acquisition_Name","Metrics_Reg","Metrics_Cyc","Metrics_Ch"),all = T)

saveRDS(allData,'CodexProjectTracking/database.rds')
```







